Fix memory growth due to geoip2 module. Add IPv6 support for geoip.
We're seeing unbounded memory growth due to the geoip2 module lookups.
Revert to the built-in nginx geoip module that uses the legacy data
format (but maxmind still provides these and maintains the legacy data
formats, so I don't think this should be a big deal).

Also switch to using the IPv6 dataset download, so that we can geocode
ipv6 addresses (tests added).

Also fix an issue with api-umbrella-geoip-auto-updater not being able to
run the "api-umbrella" reload command on dataset updates to the
less-privileged user it was running as (we may want to eventually
revisit this so that the api-umbrella user can trigger reloads, but
that's a bit more involved at this point).

One note about geoip2's memory usage, is that I had actually picked it
due to seemingly better memory characteristics in some original testing:
https://github.com/NREL/api-umbrella/commit/50258e09bcaf5347d65e26970f95882acdbfcc32
What I saw previously with the geoip2 module was that it started the
processes without much memory use, but then slowly grew as more IP
addresses were used. So some growth was to be expected, but unlike the
initial benchmarks where I'm pretty sure I saw things level off, we seem
to be seeing unbounded growth on production.

In contrast, the builtin geoip module loads the entire city database
into memory at start, so the initial memory use is higher, but then
we're not seeing any growth. Furthermore, after a bit more
investigating, I think the builtin geoip module has better memory use
overall, despite the initially higher usage. Each worker process reports
higher memory usage, which looks even worse when there's lots of worker
processes running, but it turns out this memory is shared across all the
worker processes (due to forking+copy-on-write):
https://forum.nginx.org/read.php?29,159998,160063#msg-160063 Whereas,
I'm not totally sure, but I believe the geoip2 module does not behave
this way, and each worker process does contain it's own copy of the
geoip dataset, so the memory use can actually be much higher with lots
of worker processes.

diff --git a/bin/api-umbrella-geoip-auto-updater b/bin/api-umbrella-geoip-auto-updater
--- a/bin/api-umbrella-geoip-auto-updater
+++ b/bin/api-umbrella-geoip-auto-updater
@@ -7,49 +7,68 @@ cleanup() {
 }
 trap "cleanup" EXIT
 
-REMOTE_MD5_URL="https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.md5"
-DOWNLOAD_URL="https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz"
+if [ -z "$API_UMBRELLA_SRC_ROOT" ]; then
+  echo "Error: API_UMBRELLA_SRC_ROOT environment variable is not set"
+  exit 1
+fi
+
+if [ -z "$API_UMBRELLA_DB_DIR" ]; then
+  echo "Error: API_UMBRELLA_DB_DIR environment variable is not set"
+  exit 1
+fi
+
+DOWNLOAD_URL="https://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz"
 FREQUENCY=86400 # Sleep for 1 day between runs
 
 while true; do
-  CURRENT_PATH=$API_UMBRELLA_DB_DIR/geoip2/city.mmdb
-  CURRENT_MD5=$(openssl md5 $CURRENT_PATH | awk '{print $2}')
-  REMOTE_MD5=$(curl -s -S -L $REMOTE_MD5_URL)
+  CURRENT_PATH=$API_UMBRELLA_DB_DIR/geoip/city-v6.dat
 
-  if [ "${#REMOTE_MD5}" != "32" ]; then
-    echo "$REMOTE_MD5_URL did not contain a valid MD5 checksum. Received:"
-    echo $REMOTE_MD5
-  elif [ "$REMOTE_MD5" == "$CURRENT_MD5" ]; then
-    echo "$CURRENT_PATH is already up to date (checksum: $CURRENT_MD5)"
+  # Don't attempt to redownload if the current file has recently been updated
+  # (within the last 22 hours).
+  if [[ -f $CURRENT_PATH && "$(find $CURRENT_PATH -mmin -1320)" ]]; then
+    echo "$CURRENT_PATH recently updated - skipping"
+    sleep $FREQUENCY
+    continue
+  fi
+
+  # Download the data file to a temporary path.
+  echo "Downloading new file..."
+  UNZIP_PATH=$(mktemp -t api-umbrella-geoip-auto-updater.XXXXXXXXXX)
+  DOWNLOAD_PATH="$UNZIP_PATH.gz"
+  curl --silent --show-error --fail --location --output $DOWNLOAD_PATH $DOWNLOAD_URL
+  if [ $? -ne 0 ]; then
+    echo "Error downloading $DOWNLOAD_URL"
   else
-    echo "Downloading new file..."
-    UNZIP_PATH=$(mktemp -t api-umbrella-geoip-auto-updater.XXXXXXXXXX)
-    DOWNLOAD_PATH="$UNZIP_PATH.gz"
-
-    curl -s -S -L -o $DOWNLOAD_PATH $DOWNLOAD_URL
+    # Un-gzip the downloaded file.
     gunzip -c $DOWNLOAD_PATH > $UNZIP_PATH
-    UNZIP_MD5=$(openssl md5 $UNZIP_PATH | awk '{print $2}')
-
-    if [ "$REMOTE_MD5" != "$UNZIP_MD5" ]; then
-      echo "The download file did not match the expected checksum."
-      echo "Download URL: $DOWNLOAD_URL"
-      echo "Expected checksum: $REMOTE_MD5"
-      echo "Actual checksum: $UNZIP_MD5"
-      ls -lh $DOWNLOAD_PATH $UNZIP_PATH
+    if [ $? -ne 0 ]; then
+      echo "Error unzipping $DOWNLOAD_PATH"
     else
-      mv $UNZIP_PATH $CURRENT_PATH
-      echo "Installed new $CURRENT_PATH"
+      UNZIP_MD5=$(openssl md5 $UNZIP_PATH | awk '{print $2}')
+      if [ -f $CURRENT_PATH ]; then
+        CURRENT_MD5=$(openssl md5 $CURRENT_PATH | awk '{print $2}')
+      fi
 
-      $API_UMBRELLA_SRC_ROOT/bin/api-umbrella reload
-      if [ $? == 0 ]; then
-        echo "Reloaded api-umbrella"
+      # If the new files is different, move it into place and then reload API
+      # Umbrella.
+      if [ "$UNZIP_MD5" == "$CURRENT_MD5" ]; then
+        echo "$CURRENT_PATH is already up to date (checksum: $CURRENT_MD5)"
       else
-        echo "Reloading api-umbrella failed"
+        mv $UNZIP_PATH $CURRENT_PATH
+        echo "Installed new $CURRENT_PATH"
+
+        $API_UMBRELLA_SRC_ROOT/bin/api-umbrella reload
+        if [ $? == 0 ]; then
+          echo "Reloaded api-umbrella"
+        else
+          echo "Reloading api-umbrella failed"
+        fi
       fi
     fi
-
-    rm -f $DOWNLOAD_PATH $UNZIP_PATH
   fi
+
+  # Cleanup any temp files.
+  rm -f $DOWNLOAD_PATH $UNZIP_PATH
 
   sleep $FREQUENCY
 done
